name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - '**.csproj'
      - ./templates

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Pack with dotnet
      run: dotnet pack Templates.csproj --configuration Release    

    - name: Push to Nuget
      run: dotnet nuget push ./bin/Release/Nibblebit.Templates.CommandLine.*.nupkg  -s https://www.nuget.org/ -k ${{ secrets.NUGET_API_KEY }}