name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Pack with dotnet
      run: dotnet pack Templates.csproj --configuration Release    

    - name: Push to Nuget
      run: dotnet nuget push ./bin/Release/Templates.*.nupkg  -s https://www.nuget.org/ -k ${{ secrets.NUGET_API_KEY }}